services:
  mongodb-test:
    image: mongo:7.0
    container_name: auth-mongodb-test
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: mongod --replSet rs0 --bind_ip_all --logpath /var/log/mongodb/mongod.log
    volumes:
      - mongodb_test_data:/data/db
      - mongodb_test_logs:/var/log/mongodb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_test_data:
  mongodb_test_logs: