services:
  mongodb:
    image: mongo:7.0
    container_name: auth-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: mongod --replSet rs0 --bind_ip_all --dbpath /tmp/mongodb --nojournal
    tmpfs:
      - /tmp/mongodb
    environment:
      - MONGO_INITDB_DATABASE=auth_system

  app:
    build: .
    container_name: auth-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/auth_system
      - JWT_SECRET=your-super-secret-jwt-key-here-make-it-very-long-and-secure
      - BCRYPT_ROUNDS=12
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "sleep 30 && npm run dev"
